### ISSUE TITLE
minimist versions used in this contains couple of known vulnerabilities

### ISSUE THREAD

**Issue by ipmanlk** [sematext/sematext-agent-express#4]
This package contains outdated versions of minimist that contain couple of vulnerabilities.

**Comment by otisg** [comment]
I thiiiiiink @adnanrahic just fixed that earlier today.  Could you please check the latest version?

Ip Man?  👍

**Comment by adnanrahic** [comment]
Hey @ipmanlk ! Yes, we're aware of this. It's an issue with the [gc-stats module](https://github.com/dainis/node-gcstats) and they're aware of it. You can [see here](https://github.com/dainis/node-gcstats/pull/43) that there's an open PR to be merged as soon as the maintainer sees it.

We will update our packages ASAP, once that PR gets merged.

**Comment by adnanrahic** [comment]
We forked the repo and [maintain our own fork](https://github.com/adnanrahic/node-gcstats). The dependencies are updated now.
